file_path = "./testdata"

[database]
dim = 128
metric_type = "L2"
index_type = "Flat"
version = "0.1.0"

[server]
search_url_suffix = "/search"
upsert_url_suffix = "/upsert"
port = 7000
log_level = "debug"
