name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CMAKE_VERSION: 3.31.4

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update apt
      run: sudo apt-get update
    - name: Download Build Toolkits
      run: sudo apt-get install -y build-essential wget curl
    - name: Download LLVM
      run: |
        sudo apt-get install -y lsb-release software-properties-common gnupg
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        ln -s /usr/bin/clang-19 /usr/local/bin/clang
    - name: Download OpenBlas Lib
      run: sudo apt-get install -y libblas-dev liblapack-dev
    - name: Download CMake
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz -O /tmp/cmake.tgz;
        gunzip < /tmp/cmake.tgz | tar -xf - -C /tmp/;
        sudo mv /tmp/cmake-${CMAKE_VERSION}-* /usr/local/cmake;
        ln -s /usr/local/cmake/bin/cmake /usr/local/bin/cmake
    - name: Download Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        ln -s "$HOME/.cargo/bin/cargo" /usr/local/bin/cargo
    - name: Rust Build
      run: cargo build --verbose
    - name: Run Tests
      run: cargo test --verbose
